Fix debug output of code signature entitlements

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -48,7 +48,7 @@ jobs:
       run: codesign -vvvv -R="notarized" --check-notarization ./host/temp/binary/holochain || echo "failed"
 
     - name: code-sign entitlements
-      run: codesign -d --entitlements ./host/temp/binary/holochain || echo "failed"
+      run: codesign -d --entitlements - ./host/temp/binary/holochain || echo "failed"
 
     - name: Build AD4M cli
       run: cd cli && cargo build --release
